WebApplication1/WebApplication1/Models/EstudianteViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class EstudianteViewModel
    {
        [Required(ErrorMessage = "El id del estudiante es requerido")]
        public int Id { get; set; }
        [Required(ErrorMessage = "El nombre del estudiante es requerido")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "El apellido del estudiante es requerido")]
        public string Apellido { get; set; }
        public string NombreApellido { get { return Nombre + " " + Apellido; } }
    }
}

WebApplication1/WebApplication1/Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.Repository;

namespace WebApplication1.Controllers
{
    public class EstudianteController : Controller
    {
        readonly IEstudianteRepository estudianteRepository;
        public EstudianteController(IEstudianteRepository estudianteRepository)
        {
            this.estudianteRepository = estudianteRepository;
        }

        // GET: Estudiante
        public ActionResult Index(string SearchString)
        {
            if(string.IsNullOrEmpty(SearchString))
            {
                List<EstudianteViewModel> listaEstudiantes = estudianteRepository.ObtenerEstudiantes();
                return View(listaEstudiantes);
            }
            else
            {
                List<EstudianteViewModel> listaEstudiantes = estudianteRepository.ObtenerEstudiantes().FindAll(x=>x.Nombre.Contains(SearchString) || x.Apellido.Contains(SearchString));
                ViewBag.SearchString = SearchString;
                return View(listaEstudiantes);
            }
        }

        // GET: Estudiante/Details/5
        public ActionResult Details(int id)
        {
            EstudianteViewModel estudiante = estudianteRepository.ObtenerEstudiante(id);
            return View(estudiante);
        }

        // GET: Estudiante/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Estudiante/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm]EstudianteViewModel estudiante)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    // TODO: Add insert logic here
                    estudianteRepository.CrearEstudiante(estudiante);
                    return RedirectToAction(nameof(Index));
                }
                else {
                    return View(estudiante);
                }

            }
            catch
            {
                return View();
            }
        }

        // GET: Estudiante/Edit/5
        public ActionResult Edit(int id)
        {
            EstudianteViewModel estudiante = estudianteRepository.ObtenerEstudiante(id);
            return View(estudiante);
        }

        // POST: Estudiante/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [FromForm]EstudianteViewModel estudiante)
        {
            try
            {
                estudianteRepository.ModificarEstudiante(estudiante);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Estudiante/Delete/5
        public ActionResult Delete(int id)
        {
            EstudianteViewModel estudiante = estudianteRepository.ObtenerEstudiante(id);
            return View(estudiante);
        }

        // POST: Estudiante/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, [FromForm] EstudianteViewModel estudiante)
        {
            try
            {
                // TODO: Add delete logic here
                estudianteRepository.QuitarEstudiante(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/WebApplication1/Views/Estudiante/Create.cshtml
@model WebApplication1.Models.EstudianteViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>EstudianteViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/WebApplication1/Views/Estudiante/Delete.cshtml
@model WebApplication1.Models.EstudianteViewModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EstudianteViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication1/WebApplication1/Views/Estudiante/Details.cshtml
@model WebApplication1.Models.EstudianteViewModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>EstudianteViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/WebApplication1/Views/Estudiante/Edit.cshtml
@model WebApplication1.Models.EstudianteViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>EstudianteViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/WebApplication1/Views/Estudiante/Index.cshtml
@model IEnumerable<WebApplication1.Models.EstudianteViewModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
    <form asp-controller="Estudiante" asp-action="Index" method="get">
        <p>
            Nombre/Apellido: <input type="text" name="SearchString" value="@ViewBag.SearchString"/>
            <input type="submit" value="Search" />
        </p>
    </form>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>